### ISSUE TITLE
Change geography from 2012 to 2013

### ISSUE THREAD

**Issue by courtneycl** [koopjs/koop-acs#2]
Please change the geography to the following services
Counties - 
https://www.arcgis.com/home/item.html?id=7737221015364afbae1736765953d37c
States - 
https://www.arcgis.com/home/item.html?id=06ab12f5dcaa40839729fbe49c298700

**Comment by chelm** [comment]
@sidewalkballet all good here? I updated the data. We'll just need to make sure old data gets dropped. iF you need help with that let me know.

**Comment by courtneycl** [comment]
dropped the data yesterday, I think we're good -
